export * from './config';
export * from './dept';
export * from './dict';
export * from './file';
export * from './login-log';
export * from './menu';
export * from './role';
export * from './update-log';
export * from './user';
