services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  rocketmq-namesrv:
    image: 'apache/rocketmq:5.3.2'
    ports:
      - '9876:9876'
    command: sh mqnamesrv
  rocketmq-broker:
    image: 'apache/rocketmq:5.3.2'
    environment:
      - 'NAMESRV_ADDR=rocketmq-namesrv:9876'
    ports:
      - '10909:10909'
      - '10911:10911'
      - '10912:10912'
    depends_on:
      - rocketmq-namesrv
    command: sh mqbroker
  rocketmq-proxy:
    image: 'apache/rocketmq:5.3.2'
    environment:
      - 'NAMESRV_ADDR=rocketmq-namesrv:9876'
    ports:
      - '8080:8080'
      - '8081:8081'
    depends_on:
      - rocketmq-namesrv
      - rocketmq-broker
    restart: on-failure
    command: sh mqproxy
