logging:
  access:
    enabled: true #是否启用access日志，true/false，默认开启
  level:
    root: INFO  #全局日志级别
    com.travis: DEBUG #业务代码
  pattern:
    #该配置仅控制dev环境终端输出格式，生产输出为json
    console: >
      %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint}
      %clr(%level)
      %clr(%replace(%X{request_id}){'^(.+)$',' [$1]'}){yellow}
      %clr([%thread]){magenta}
      %clr(%logger{36}:%line){cyan}
      - %msg%n%wEx

management:
  endpoints:
    web:
      exposure:
        include: modulith

# RocketMQ配置
rocketmq:
  # 消费者配置(全局默认配置)
  consumer:
    # 是否启用消息轨迹，本地开发可以关闭消息轨迹
    enable-msg-trace: false
    # Proxy 模式访问，端口为 Docker 映射的 8081
    endpoints: 127.0.0.1:8081
  # 生产者配置
  producer:
    # 是否启用消息轨迹，本地开发可以关闭消息轨迹
    enable-msg-trace: false
    # Proxy 模式访问，端口为 Docker 映射的 8081
    endpoints: 127.0.0.1:8081

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/travis_monolith?serverTimezone=${travis.web.time-zone:UTC}&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  modulith:
    runtime:
      verification-enabled: true  #是否启用运行时验证，true/false

travis:
  web:
    domain: http://127.0.0.1